In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [4]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9],[10,11,12]]
x = np.array(my_matrix)
print(x)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [9]:
print(np.arange(0,5))
print(np.arange(0,20,2))

[0 1 2 3 4]
[ 0  2  4  6  8 10 12 14 16 18]


In [11]:
print(np.zeros(10))
print(np.zeros((3,5)))

[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]]


In [14]:
print(np.ones(10))
print(np.ones((5,5)))

[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
[[ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]]


In [22]:
np.linspace(0,20,6)

array([  0.,   4.,   8.,  12.,  16.,  20.])

In [21]:
# identity matrix
np.eye(8)

array([[ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.]])

In [24]:
# np does random. uniform distribution
np.random.rand(10)
np.random.rand(4,4)

array([[ 0.16261725,  0.48449486,  0.27522985,  0.74305799],
       [ 0.84111564,  0.52929096,  0.91987259,  0.86265878],
       [ 0.05140654,  0.47619775,  0.8532252 ,  0.17607208],
       [ 0.78075357,  0.93300761,  0.04608477,  0.1222551 ]])

In [26]:
# np random standard normal distribution (gaussian distribution)
np.random.randn(10)
np.random.randn(4,4)

array([[-0.08862984, -1.94096948, -1.14393774,  0.79970015],
       [ 0.24811627, -0.30222168, -0.79411244, -0.00756072],
       [ 1.52765753,  0.27270411,  2.25660545,  0.66431218],
       [ 2.0034754 , -1.53183161, -0.60454349, -1.8423824 ]])

In [29]:
np.random.randint(0,100,10)

array([75, 50,  7, 66, 79, 76,  9, 23, 34, 44])

In [52]:
arr = np.arange(25)
ranarr = np.random.randint(0,50,10)
arr.reshape(5,5)
arr.reshape(5,5).shape
arr.dtype
ranarr.max() # max value
ranarr.argmax() # index of max value
ranarr.min() #min value
ranarr.argmin()

2

In [55]:
arr = np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [56]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [57]:
arr*arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [59]:
arr*5

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [60]:
arr**2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [61]:
arr + 20

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [62]:
np.sqrt(arr)

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ])

In [63]:
np.exp(arr)

array([  1.00000000e+00,   2.71828183e+00,   7.38905610e+00,
         2.00855369e+01,   5.45981500e+01,   1.48413159e+02,
         4.03428793e+02,   1.09663316e+03,   2.98095799e+03,
         8.10308393e+03])

In [66]:
np.max(arr)
arr.max()

9

In [67]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [68]:
np.log(arr)

/usr/local/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([       -inf,  0.        ,  0.69314718,  1.09861229,  1.38629436,
        1.60943791,  1.79175947,  1.94591015,  2.07944154,  2.19722458])