In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [13]:
arr = np.arange(0,11)
arr[8]
arr[2:5]
arr[-2]
arr[5:]
arr[:5]
# broadcasting
arr[0:5] = 100
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [19]:
# ar2 is just a pointer to a slice of arr... this could be dangerous if you only 
# want a section of the data and want to keep the original.
# any modifications to ar2 will affect arr
# this is about saving and managing memory when dealing with large datasets.
# need to use .copy() to make a copy of the data
arr = np.arange(0,11)
ar2 = arr[2:8]
ar2[:] = 99
ar2
arr

array([ 0,  1, 99, 99, 99, 99, 99, 99,  8,  9, 10])

In [22]:
arr = np.arange(0,11)
arr_copy = arr.copy()
print(arr, arr_copy)

[ 0  1  2  3  4  5  6  7  8  9 10] [ 0  1  2  3  4  5  6  7  8  9 10]


In [34]:
# 2d arrays or a matrix
# mat[row, column]
# mat[row][column]
mat = np.array([[2,4,6],[5,10,15],[10,20,30]])
print(mat)
mat[0]
mat[2]
mat[0][0]
mat[1][1]
mat[1][1:]
mat[1,2]

[[ 2  4  6]
 [ 5 10 15]
 [10 20 30]]


15

In [42]:
mat = np.array([[2,4,6],[5,10,15],[10,20,30]])
print(mat)
mat[2,1]
mat[2,1:]
mat[0:2,1:]
mat[1:,1:]

[[ 2  4  6]
 [ 5 10 15]
 [10 20 30]]


array([[10, 15],
       [20, 30]])

In [48]:
# Conditional Selection
ar = np.arange(1,11)
bool_ar = ar > 4
ar[bool_ar]
# easier
ar[ar>4]
ar[ar<=7]

array([1, 2, 3, 4, 5, 6, 7])