In [1]:
x = 'funkyday'

In [2]:
x[0]

'f'

In [4]:
x[5:8]

'day'

In [6]:
if(5 == 15/3):
    print("farts")

farts


In [14]:
def simplefunc(x):
    x=x**x
    return(x)

In [23]:
foo = simplefunc(3.1459)

In [24]:
print(foo)

36.80066978887869


In [70]:
x = ['john', 'linda', 'noah', 'jacob']

In [56]:
x[0]

'john'

In [57]:
x[1][0:3]

'lin'

In [58]:
x[-1][-3:]

'cob'

In [71]:
x.append('bob')

In [72]:
x

['john', 'linda', 'noah', 'jacob', 'bob']

In [73]:
x.remove('bob')

In [74]:
x

['john', 'linda', 'noah', 'jacob']

In [75]:
x.append('bob')

In [76]:
x

['john', 'linda', 'noah', 'jacob', 'bob']

In [77]:
x[4]='sara'

In [78]:
x

['john', 'linda', 'noah', 'jacob', 'sara']

In [79]:
del x[4]

In [80]:
x

['john', 'linda', 'noah', 'jacob']

In [81]:
y = ['bob', 'sara', 'bert']

In [82]:
x.extend(y)

In [83]:
x

['john', 'linda', 'noah', 'jacob', 'bob', 'sara', 'bert']

In [84]:
len(x)

7

In [86]:
x[0:4]

['john', 'linda', 'noah', 'jacob']

In [87]:
x[:4]

['john', 'linda', 'noah', 'jacob']

In [89]:
x[4:]

['bob', 'sara', 'bert']

In [90]:
x[-3:]

['bob', 'sara', 'bert']

In [93]:
x.index('jacob')

3

In [94]:
# list of lists
z =[x, y]

In [95]:
z

[['john', 'linda', 'noah', 'jacob', 'bob', 'sara', 'bert'],
 ['bob', 'sara', 'bert']]

In [96]:
z[1]

['bob', 'sara', 'bert']

In [97]:
z[0]

['john', 'linda', 'noah', 'jacob', 'bob', 'sara', 'bert']

In [99]:
x.sort()

In [100]:
x

['bert', 'bob', 'jacob', 'john', 'linda', 'noah', 'sara']

In [102]:
x.sort(reverse=True)

In [103]:
x

['sara', 'noah', 'linda', 'john', 'jacob', 'bob', 'bert']

In [104]:
(a,b,c) = (1,2,3)

In [106]:
d = (4,5,6,7,8,9)

In [107]:
type(d)

tuple

In [108]:
d[0]

4

In [110]:
d[0]=42 #tuples are immutable

TypeError: 'tuple' object does not support item assignment

In [111]:
e = (2,4,6,8,10)

In [112]:
f = [d,e] #list of tuples

In [113]:
f 

[(4, 5, 6, 7, 8, 9), (2, 4, 6, 8, 10)]

In [114]:
(age, years) = "43,18".split(',')

In [115]:
print(str(age) + " " + str(years))

43 18


In [116]:
goodmans = {'john':43, 'linda':46, 'noah':8, 'jacob':6}

In [118]:
goodmans

{'jacob': 6, 'john': 43, 'linda': 46, 'noah': 8}

In [124]:
goodmans['jacob']

6

In [127]:
goodmans['liko'] = 15
goodmans['daisy'] = 12
goodmans['floof'] = 2

In [128]:
goodmans

{'daisy': 12,
 'floof': 2,
 'jacob': 6,
 'john': 43,
 'liko': 15,
 'linda': 46,
 'noah': 8}

In [129]:
goodmans['floof'] = 42

In [130]:
goodmans

{'daisy': 12,
 'floof': 42,
 'jacob': 6,
 'john': 43,
 'liko': 15,
 'linda': 46,
 'noah': 8}

In [131]:
dep_workers = {'dep_1': "peter", 'dep_2':['jen', 'mike', 'tom']}

In [132]:
dep_workers

{'dep_1': 'peter', 'dep_2': ['jen', 'mike', 'tom']}

In [133]:
dep_workers['dep_2']

['jen', 'mike', 'tom']

In [134]:
dep_workers['dep_1']

'peter'

In [135]:
# Empty dict
Team = {}

In [136]:
Team['Boss'] = 'Bob'
Team['Worker1'] = 'Jerry'
Team['Worker2'] = 'Lori'

In [137]:
Team

{'Boss': 'Bob', 'Worker1': 'Jerry', 'Worker2': 'Lori'}

In [138]:
Team.get('Worker1')

'Jerry'

In [140]:
Team.get('Floof') # Won't return error if key doesn' exist

In [141]:
even = [0,2,4,6,8,10,12,14,16,18,20]

In [142]:
for x in even:
    print(x**2)

0
4
16
36
64
100
144
196
256
324
400


In [143]:
y=[]
for x in even:
    y.append(x**2)

In [144]:
y

[0, 4, 16, 36, 64, 100, 144, 196, 256, 324, 400]

In [145]:
count=0
for x in even:
    even[count]=x**2
    count = count + 1

In [146]:
even

[0, 4, 16, 36, 64, 100, 144, 196, 256, 324, 400]

In [151]:
count = 0
while(count < len(even)):
    print(even[count])
    count += 1

0
4
16
36
64
100
144
196
256
324
400


In [161]:
for x in range(0,100,10):
    print(x)

0
10
20
30
40
50
60
70
80
90


In [163]:
for y in range(10):
    print(y**y)

1
1
4
27
256
3125
46656
823543
16777216
387420489


In [172]:
for z in range(20):
    if z%2 == 0:
        print(z, end=' ')
    else:
        print('odd', end=' ')
        

0 odd 2 odd 4 odd 6 odd 8 odd 10 odd 12 odd 14 odd 16 odd 18 odd 

In [174]:
def countlt(numlist, lessthan):
    total = 0
    for x in numlist:
        if x < lessthan:
            total += 1
    return(total)

In [179]:
print(even)
countlt(even, 100)

[0, 4, 16, 36, 64, 100, 144, 196, 256, 324, 400]


5

In [180]:
goodmans

{'daisy': 12,
 'floof': 42,
 'jacob': 6,
 'john': 43,
 'liko': 15,
 'linda': 46,
 'noah': 8}

In [182]:
for key in goodmans:
    print(key + " is " + str(goodmans[key]) + " years old." )

john is 43 years old.
linda is 46 years old.
noah is 8 years old.
jacob is 6 years old.
liko is 15 years old.
daisy is 12 years old.
floof is 42 years old.


In [184]:
import numpy as np

In [187]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])

In [188]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [204]:
a.shape

(4, 4)

In [189]:
a.diagonal()

array([ 1,  6, 11, 16])

In [191]:
a.argmax()

15

In [192]:
a.argmin()

0

In [196]:
a[1]

array([5, 6, 7, 8])

In [197]:
a[1][2]

7

In [205]:
a[1][2] =42

In [206]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6, 42,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [207]:
for x in a:
    for y in x:
        print(y)

1
2
3
4
5
6
42
8
9
10
11
12
13
14
15
16


In [208]:
a.transpose()

array([[ 1,  5,  9, 13],
       [ 2,  6, 10, 14],
       [ 3, 42, 11, 15],
       [ 4,  8, 12, 16]])

In [209]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6, 42,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [210]:
a*2

array([[ 2,  4,  6,  8],
       [10, 12, 84, 16],
       [18, 20, 22, 24],
       [26, 28, 30, 32]])

In [212]:
np.sqrt(a)

array([[ 1.        ,  1.41421356,  1.73205081,  2.        ],
       [ 2.23606798,  2.44948974,  6.4807407 ,  2.82842712],
       [ 3.        ,  3.16227766,  3.31662479,  3.46410162],
       [ 3.60555128,  3.74165739,  3.87298335,  4.        ]])

In [213]:
import random

In [214]:
prob = random.random()

In [215]:
prob

0.40551525411061806

In [216]:
probnp = np.random.random()

In [217]:
probnp

0.11827878112049106

In [221]:
number = random.randint(1,100)

In [224]:
number

12

In [223]:
numnp = np.random.randint(1,100)

In [ ]:
print

In [225]:
numnp

28

In [226]:
np.random.randint(1,100,(4,6))

array([[ 5, 40, 27, 21, 58, 77],
       [69, 72, 73,  4, 35, 42],
       [92, 86, 90, 11, 62, 93],
       [26, 43, 96, 76, 91, 93]])

In [227]:
np.random.randint(1,100,(5,5))

array([[86,  4, 36, 42, 90],
       [83, 23, 38, 97, 30],
       [16, 58, 88, 36, 23],
       [ 2, 22, 23, 21, 56],
       [53, 80, 22, 72, 92]])

In [228]:
import time
import numpy as np
import pandas as pd
from pandas_datareader import data as wb
import quandl
quandl.ApiConfig.api_key = 'JgrixskwB3MtGDkJtxms'
import matplotlib.pyplot as plt
%matplotlib inline

In [231]:
tickers = ['PG','MSFT','AAPL','AMZN']
sec_data = pd.DataFrame()

for t in tickers:
    sec_data[t] = wb.DataReader(t, data_source='yahoo', start='2007-01-01')['Adj Close']
    #time.sleep(20)


In [232]:
import pandas as pd
import numpy as np
from pandas_datareader import data as wb
 
stocks = ['PG', 'IBM']
portfolio = pd.DataFrame()
for t in stocks:
    portfolio[t] = wb.DataReader(t, data_source='yahoo', start='2015-01-01')['Adj Close']
portfolio

PG         IBM
Date                             
2015-01-02  82.832062  146.984680
2015-01-05  82.438232  144.671860
2015-01-06  82.062714  141.551895
2015-01-07  82.493172  140.626755
2015-01-08  83.436539  143.683289
2015-01-09  82.658043  144.309113
2015-01-12  82.355789  141.887466
2015-01-13  82.703842  142.223053
2015-01-14  82.419922  141.307007
2015-01-15  82.300850  140.191422
2015-01-16  83.573906  142.522339
2015-01-20  83.518974  142.350021
2015-01-21  83.688683  137.942108
2015-01-22  84.509621  140.935135
2015-01-23  83.089149  141.370483
2015-01-26  82.627930  141.814926
2015-01-27  79.777748  139.375122
2015-01-28  78.541740  137.452347
2015-01-29  79.021370  141.016754
2015-01-30  77.748489  139.048615
2015-02-02  78.514061  140.273056
2015-02-03  79.279648  143.728622
2015-02-04  79.132057  142.359085
2015-02-05  79.971451  143.220718
2015-02-06  78.966026  143.138519
2015-02-09  78.449501  142.252579
2015-02-10  78.763115  144.819046
2015-02-11  78.993721  144.490265
2015-02-12  79.353447  144.782547
2015-02-13  79.233528  146.499603
...               ...         ...
2017-09-07  92.970001  142.899994
2017-09-08  92.839996  142.449997
2017-09-11  93.989998  144.860001
2017-09-12  93.510002  145.759995
2017-09-13  93.550003  145.990005
2017-09-14  93.550003  145.539993
2017-09-15  93.269997  144.820007
2017-09-18  93.150002  144.550003
2017-09-19  94.169998  144.389999
2017-09-20  94.400002  145.880005
2017-09-21  92.639999  145.259995
2017-09-22  92.239998  145.130005
2017-09-25  92.720001  145.869995
2017-09-26  92.650002  146.559998
2017-09-27  90.870003  145.660004
2017-09-28  90.889999  145.660004
2017-09-29  90.980003  145.080002
2017-10-02  91.769997  146.660004
2017-10-03  92.120003  146.779999
2017-10-04  92.419998  146.479996
2017-10-05  92.029999  146.720001
2017-10-06  92.330002  146.479996
2017-10-09  92.120003  147.389999
2017-10-10  91.620003  148.500000
2017-10-11  91.459999  147.619995
2017-10-12  92.150002  147.029999
2017-10-13  93.040001  147.100006
2017-10-16  93.139999  146.830002
2017-10-17  92.800003  146.539993
2017-10-18  92.769997  159.529999

[705 rows x 2 columns]