## Working with Arrays

Create a 3 x 6-dimensional array, containing only float values. 

In [1]:
import numpy as np

In [2]:
a = np.array([[0.5, 1.35, 2.6, 3.98, 4.23, 18.0], [4.4, 5.65, 6.12, 7.13, 60.06, 12.0], [1.5, 5.5, 6.25, 6.25, 7.05, 9.10]])
a

array([[  0.5 ,   1.35,   2.6 ,   3.98,   4.23,  18.  ],
       [  4.4 ,   5.65,   6.12,   7.13,  60.06,  12.  ],
       [  1.5 ,   5.5 ,   6.25,   6.25,   7.05,   9.1 ]])

Check the dimension you have created is correct (use “*.shape*”)

In [4]:
a.shape

(3L, 6L)

Substitute the 5th element from the 2nd row with 19.75.

In [5]:
a[1,4] = 19.75
a

array([[  0.5 ,   1.35,   2.6 ,   3.98,   4.23,  18.  ],
       [  4.4 ,   5.65,   6.12,   7.13,  19.75,  12.  ],
       [  1.5 ,   5.5 ,   6.25,   6.25,   7.05,   9.1 ]])

Extract the 2nd and the 3rd row of the array you created. 

In [6]:
a[1]

array([  4.4 ,   5.65,   6.12,   7.13,  19.75,  12.  ])

In [7]:
a[2]

array([ 1.5 ,  5.5 ,  6.25,  6.25,  7.05,  9.1 ])