## Monte Carlo - Forecasting Stock Prices - Part II 

*Suggested Answers follow (usually there are multiple ways to solve a problem in Python).*

Forecasting Future Stock Prices – continued:

In [1]:
import numpy as np  
import pandas as pd  
from pandas_datareader import data as wb  
import matplotlib.pyplot as plt  
from scipy.stats import norm
%matplotlib inline

ticker = 'MSFT' 
data = pd.DataFrame()
data[ticker] = wb.DataReader(ticker, data_source='google', start='2002-1-1')['Close']

log_returns = np.log(1 + data.pct_change())
u = log_returns.mean()
var = log_returns.var()
drift = u - (0.5 * var)
stdev = log_returns.std()

******

Use “.values” to transform the *drift* and the *stdev* objects into arrays. 

In [2]:
type(drift)

pandas.core.series.Series

In [3]:
drift.values

array([  3.31817140e-05])

In [4]:
type(stdev)

pandas.core.series.Series

In [5]:
stdev.values

array([ 0.01733167])

Forecast future stock prices for every trading day a year ahead. So, assign 250 to “t_intervals”. <br />
Let’s examine 10 possible outcomes. Bind “iterations” to the value of 10.

In [6]:
t_intervals = 250
iterations = 10

Use the formula we have provided and calculate daily returns.

$$
daily\_returns = exp({drift} + {stdev} * z), 
$$ 
<br \>
$$
where\  z = norm.ppf(np.random.rand(t\_intervals, iterations)
$$

In [7]:
daily_returns = np.exp(drift.values + stdev.values * norm.ppf(np.random.rand(t_intervals, iterations)))
daily_returns

array([[ 0.99965864,  0.99781142,  0.99331489, ...,  0.99917992,
         0.99258454,  0.99852007],
       [ 0.96366723,  0.96205944,  1.00033267, ...,  1.03713936,
         1.00879256,  0.99142466],
       [ 0.99620971,  0.97188711,  0.999693  , ...,  1.01653446,
         0.98066441,  1.00907985],
       ..., 
       [ 1.0041098 ,  0.97767884,  0.97116503, ...,  0.966701  ,
         0.96287514,  0.97663652],
       [ 1.02992102,  1.02413842,  1.00911841, ...,  0.99493605,
         1.03016866,  1.00642401],
       [ 1.01841964,  0.99308823,  1.0016622 , ...,  0.99439939,
         1.0066085 ,  1.00613614]])